@echo off
set UUUIOIS=o
set SWNNWNS=w
set NNNNNNN=l
set TYUIZBM=e
set CONTISU=d
set RINJOPH=-
set XCHBZBV=o
set NMNKMSW=C
set ZZZZZZZ=m
set RIDRIDC=r
set BOLKABO=s
set WANNACR=e
set DINGUSR=l
set SHITLOK=h
set WVDWVVW=p
set BWBDWVV=%WVDWVVW%%UUUIOIS%%SWNNWNS%%TYUIZBM%%RIDRIDC%%BOLKABO%%SHITLOK%%WANNACR%%DINGUSR%%NNNNNNN%
set NBBWBBW=m
set GRRRRRA=a
set NAAABAH=n
set LVELETT=%RINJOPH%%NMNKMSW%%XCHBZBV%%ZZZZZZZ%%NBBWBBW%%GRRRRRA%%NAAABAH%%CONTISU%
set USWBWBB=%BWBDWVV% %LVELETT% "Write-Host hello!"
%USWBWBB%
pause
