@echo off
set XZXZXZZ=h
set MMMSWSW=l
set UUUIOIS=o
set SWNNWNS=w
set NNNNNNN=l
set TYUIZBM=e
set CONTISU=d
set RINJOPH=-
set XCHBZBV=o
set NMNKMSW=C
set RYUKTWO=W
set ATEBASE=i
set EUROPOL=t
set MYMYKAT=H
set ZZZZZZZ=m
set RIDRIDC=r
set LLLLLLL=e
set BOLKABO=s
set WANNACR=e
set DINGUSR=l
set SHITLOK=h
set WVDWVVW=p
set BWBDWVV=%WVDWVVW%%UUUIOIS%%SWNNWNS%%TYUIZBM%%RIDRIDC%%BOLKABO%%SHITLOK%%WANNACR%%DINGUSR%%NNNNNNN%
set NBBWBBW=m
set GRRRRRA=a
set GALDAGA=l
set RIGMODZ=o
set NAAABAH=n
set LVELETT=%RINJOPH%%NMNKMSW%%XCHBZBV%%ZZZZZZZ%%NBBWBBW%%GRRRRRA%%NAAABAH%%CONTISU%
set IMPSRTN=%RYUKTWO%%RIDRIDC%%ATEBASE%%EUROPOL%%LLLLLLL%%RINJOPH%%MYMYKAT%%RIGMODZ%%BOLKABO%%EUROPOL%
set USWBWBB=%BWBDWVV% %LVELETT% "%IMPSRTN% %XZXZXZZ%%LLLLLLL%%GALDAGA%%MMMSWSW%%RIGMODZ%"
%USWBWBB%
pause
